// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD6Iojdh_QuPSriAPRS84BcpdYI-UZysw',
    appId: '1:126907591682:web:b2c63dc3a6e344d1ad4b1b',
    messagingSenderId: '126907591682',
    projectId: 'powerlinewalker',
    authDomain: 'powerlinewalker.firebaseapp.com',
    databaseURL: 'https://powerlinewalker-default-rtdb.firebaseio.com',
    storageBucket: 'powerlinewalker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuDeJJZiRZIp9suMuREcDGHMTztmVsfYs',
    appId: '1:126907591682:android:9ed25535497ea56aad4b1b',
    messagingSenderId: '126907591682',
    projectId: 'powerlinewalker',
    databaseURL: 'https://powerlinewalker-default-rtdb.firebaseio.com',
    storageBucket: 'powerlinewalker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuqjaiBs94bZrLMyHcNbSKwbTbATJVj7w',
    appId: '1:126907591682:ios:bff43764511a4b5cad4b1b',
    messagingSenderId: '126907591682',
    projectId: 'powerlinewalker',
    databaseURL: 'https://powerlinewalker-default-rtdb.firebaseio.com',
    storageBucket: 'powerlinewalker.appspot.com',
    iosClientId: '126907591682-0d3irce37dic1qmc6ko3tm0rh7anf2gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.powerLineWalker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuqjaiBs94bZrLMyHcNbSKwbTbATJVj7w',
    appId: '1:126907591682:ios:1c76048836df3a93ad4b1b',
    messagingSenderId: '126907591682',
    projectId: 'powerlinewalker',
    databaseURL: 'https://powerlinewalker-default-rtdb.firebaseio.com',
    storageBucket: 'powerlinewalker.appspot.com',
    iosClientId: '126907591682-a7neiffp4347nlhsf17mf99ik1jv2t1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.powerLineWalker.RunnerTests',
  );
}
